/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.rm.lavarapidorm.gui;

import com.rm.lavarapidorm.persistencia.OpcoesBD;
import java.awt.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Renato
 */
public class TelaConfiguracoes extends javax.swing.JFrame {
    private static boolean isOpen = false;
    private Dimension initialSize = this.getSize();
    
    /**
     * Creates new form TelaConfigurações
     */
    public TelaConfiguracoes() {
        initComponents();
        setLocationRelativeTo(null);
        initialSize = this.getSize();
        ZoomUtils.resetStoredProperties();
        ZoomUtils.storeOriginalProperties(jPanel1);
        
        ImageIcon img = new ImageIcon(getClass().getResource("/configuracoes.png"));        
        setIconImage(img.getImage());
        
        ImageIcon iconClaro = new ImageIcon(getClass().getResource("/claro.png"));
        ImageIcon iconEscuro = new ImageIcon(getClass().getResource("/escuro.png"));
        btnClaro.setIcon(iconClaro);
        btnEscuro.setIcon(iconEscuro);
        
        if (Boolean.parseBoolean(TelaLogin.tema)) { 
        Color escuro = new Color(46, 46, 46);
        
        labelComQuebra.setName("ignorar");        
        labelComQuebra.setBackground(new Color(46, 46, 46));
        labelComQuebra.setForeground(Color.WHITE);
        
        labelComQuebra2.setName("ignorar");
        labelComQuebra2.setBackground(escuro);
        labelComQuebra2.setForeground(Color.WHITE);}
        
        SpinnerNumberModel modelLavagens = new SpinnerNumberModel(
                TelaInicial.lavagens != null ? TelaInicial.lavagens : 0, // Valor inicial
                0,                                                             // Valor mínimo
                Integer.MAX_VALUE,                                            // Valor máximo
                1                                                              // Incremento
        );
        
        SpinnerNumberModel modelDias = new SpinnerNumberModel(
                TelaInicial.dias != null ? TelaInicial.dias : 0,           // Valor inicial
                0,                                                          // Valor mínimo
                Integer.MAX_VALUE,                                         // Valor máximo
                1                                                           // Incremento
        );
        
        spinQntLava.setModel(modelLavagens);
        spinQntDias.setModel(modelDias);
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                isOpen = false;
            }

            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                isOpen = false;
            }
        });
    }
    @Override
    public void setVisible(boolean b) {
        TelaLogin.temaEscuro(this, getContentPane());
        if (TelaLogin.conf == 0) { labelComQuebra2.setVisible(false); cBoxTelSim.setVisible(false); cBoxTelNao.setVisible(false); jScrollPane2.setVisible(false); cBoxLavaSim.setEnabled(false); cBoxLavaNao.setEnabled(false); spinQntLava.setEnabled(false); spinQntDias.setEnabled(false); }
        if (!TelaInicial.funcGratis) { spinQntLava.setEnabled(false); spinQntLava.setValue(Integer.valueOf("0")); spinQntDias.setEnabled(false); spinQntDias.setValue(Integer.valueOf("0")); }
        if (!isOpen) {
            isOpen = true;
            super.setVisible(b);
        } else {
            JOptionPane.showMessageDialog(this, "Esta janela já está aberta!");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnEscuro = new javax.swing.JButton();
        btnClaro = new javax.swing.JButton();
        cBoxTelSim = new javax.swing.JCheckBox();
        cBoxTelNao = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        cBoxLavaSim = new javax.swing.JCheckBox();
        cBoxLavaNao = new javax.swing.JCheckBox();
        spinQntLava = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        spinQntDias = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        labelComQuebra = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        labelComQuebra2 = new javax.swing.JTextArea();
        btnVoltar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configurações");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Tema:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnEscuro.setToolTipText("Tema escuro");
        btnEscuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscuroActionPerformed(evt);
            }
        });
        jPanel1.add(btnEscuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 43, 38));

        btnClaro.setToolTipText("Tema claro");
        btnClaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClaroActionPerformed(evt);
            }
        });
        jPanel1.add(btnClaro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 43, 38));

        cBoxTelSim.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cBoxTelSim.setText("Sim");
        cBoxTelSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxTelSimActionPerformed(evt);
            }
        });
        jPanel1.add(cBoxTelSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        cBoxTelNao.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cBoxTelNao.setText("Não");
        cBoxTelNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxTelNaoActionPerformed(evt);
            }
        });
        jPanel1.add(cBoxTelNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("Lavagem grátis");
        jLabel3.setToolTipText("Habilitar/desabilitar a função de lavagem gratis");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        cBoxLavaSim.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cBoxLavaSim.setText("Sim");
        cBoxLavaSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxLavaSimActionPerformed(evt);
            }
        });
        jPanel1.add(cBoxLavaSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        cBoxLavaNao.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cBoxLavaNao.setText("Não");
        cBoxLavaNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxLavaNaoActionPerformed(evt);
            }
        });
        jPanel1.add(cBoxLavaNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        spinQntLava.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        spinQntLava.setMaximumSize(new java.awt.Dimension(83, 33));
        spinQntLava.setMinimumSize(new java.awt.Dimension(83, 33));
        spinQntLava.setPreferredSize(new java.awt.Dimension(83, 33));
        jPanel1.add(spinQntLava, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setText("Dias de tempo limite:");
        jLabel5.setToolTipText("Quantidade de dias para alcançaar as lavagens necessárias para receber uma lavagem grátis");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        spinQntDias.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        spinQntDias.setMaximumSize(new java.awt.Dimension(83, 33));
        spinQntDias.setMinimumSize(new java.awt.Dimension(83, 33));
        spinQntDias.setPreferredSize(new java.awt.Dimension(83, 33));
        jPanel1.add(spinQntDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        labelComQuebra.setEditable(false);
        labelComQuebra.setColumns(20);
        labelComQuebra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelComQuebra.setRows(5);
        labelComQuebra.setText("Quantidade de lavagens\npara lavagem grátis:");
        labelComQuebra.setToolTipText("Lavagens necessárias para receber uma lavagem grátis");
        labelComQuebra.setMargin(new java.awt.Insets(2, 0, 2, 6));
        jScrollPane1.setViewportView(labelComQuebra);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 192, 63));

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        labelComQuebra2.setEditable(false);
        labelComQuebra2.setColumns(20);
        labelComQuebra2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelComQuebra2.setRows(5);
        labelComQuebra2.setText("Exibir \"Telefone\" \npara funcionários:");
        labelComQuebra2.setToolTipText("Ativar/desativar a coluna 'telefone' para funcionarios na Listagem Carros");
        labelComQuebra2.setMargin(new java.awt.Insets(2, 0, 2, 6));
        jScrollPane2.setViewportView(labelComQuebra2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 149, 61));

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVoltar.setText("< Voltar");
        btnVoltar.setToolTipText("Voltar a tela inicial");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 124, 41));

        btnConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConfirmar.setText("Confirmar");
        btnConfirmar.setToolTipText("Aplicar configurações");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 124, 41));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClaroActionPerformed
        TelaLogin.tema = "false";
        TelaLogin.temaEscuro(this, getContentPane());
        
        labelComQuebra.setBackground(Color.WHITE);
        labelComQuebra.setForeground(Color.BLACK);
        
        labelComQuebra2.setBackground(Color.WHITE);
        labelComQuebra2.setForeground(Color.BLACK);
        
        btnClaro.setEnabled(false);
        btnEscuro.setEnabled(true);         
    }//GEN-LAST:event_btnClaroActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        TelaLogin.temaEscuro(this, getContentPane());
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnEscuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscuroActionPerformed
        TelaLogin.tema = "true";
        TelaLogin.temaEscuro(this, getContentPane());
        
        labelComQuebra.setBackground(new Color(46, 46, 46));
        labelComQuebra.setForeground(Color.WHITE);
        
        labelComQuebra2.setBackground(new Color(46, 46, 46));
        labelComQuebra2.setForeground(Color.WHITE);
        
        btnEscuro.setEnabled(false);
        btnClaro.setEnabled(true);             
    }//GEN-LAST:event_btnEscuroActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (Boolean.parseBoolean(TelaLogin.tema)) { btnEscuro.setEnabled(false); } else {btnClaro.setEnabled(true);}
        if (TelaInicial.funcGratis) { cBoxLavaSim.setSelected(true); cBoxLavaSim.setEnabled(false); } else { cBoxLavaNao.setSelected(true); cBoxLavaNao.setEnabled(false); }
        if (TelaInicial.telefone) { cBoxTelSim.setSelected(true); cBoxTelSim.setEnabled(false); } else { cBoxTelNao.setSelected(true); cBoxTelNao.setEnabled(false); }
    }//GEN-LAST:event_formWindowOpened

    private void cBoxLavaNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxLavaNaoActionPerformed
    cBoxLavaSim.setSelected(false);
    cBoxLavaSim.setEnabled(true);
    cBoxLavaNao.setEnabled(false);
            
    spinQntLava.setEnabled(false); spinQntLava.setValue(Integer.valueOf("0"));
    spinQntDias.setEnabled(false); spinQntDias.setValue(Integer.valueOf("0"));
    }//GEN-LAST:event_cBoxLavaNaoActionPerformed

    private void cBoxLavaSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxLavaSimActionPerformed
    cBoxLavaNao.setSelected(false);
    cBoxLavaSim.setEnabled(false);
    cBoxLavaNao.setEnabled(true);
            
    spinQntLava.setEnabled(true); spinQntLava.setValue(TelaInicial.lavagens);
    spinQntDias.setEnabled(true); spinQntDias.setValue(TelaInicial.dias);
    }//GEN-LAST:event_cBoxLavaSimActionPerformed

    private void cBoxTelNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxTelNaoActionPerformed
        cBoxTelSim.setSelected(false);
        cBoxTelSim.setEnabled(true);
        cBoxTelNao.setEnabled(false);
    }//GEN-LAST:event_cBoxTelNaoActionPerformed

    private void cBoxTelSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxTelSimActionPerformed
        cBoxTelNao.setSelected(false);
        cBoxTelSim.setEnabled(false);
        cBoxTelNao.setEnabled(true);
    }//GEN-LAST:event_cBoxTelSimActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
/*  Dimension newSize = this.getSize();
    double scaleX = newSize.getWidth() / initialSize.getWidth();
    double scaleY = newSize.getHeight() / initialSize.getHeight();
    double scale = Math.min(scaleX, scaleY); // Escala proporcional
    
    ZoomUtils.updateComponentSize(jPanel1, scale); */
    }//GEN-LAST:event_formComponentResized

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if (!cBoxTelSim.isSelected() && !cBoxTelNao.isSelected()) { JOptionPane.showMessageDialog(null, "Marque uma das opções!"); return; }
        if (!cBoxLavaSim.isSelected() && !cBoxLavaNao.isSelected()) { JOptionPane.showMessageDialog(null, "Marque uma das opções!"); return; }
        if (cBoxLavaSim.isSelected()) { if((Integer)spinQntLava.getValue() == 0 || (Integer)spinQntDias.getValue() == 0) { JOptionPane.showMessageDialog(null, "O valor 0 não é aceito!"); return;} }

        TelaInicial.funcGratis = cBoxLavaSim.isSelected();      if (cBoxLavaSim.isSelected()) {
            TelaInicial.lavagens = (Integer) spinQntLava.getValue();
            TelaInicial.dias = (Integer) spinQntDias.getValue();                                  }
        TelaInicial.telefone = cBoxTelSim.isSelected();

        OpcoesBD OBD = new OpcoesBD();
        OBD.salvarConfiguracoes();

        JOptionPane.showMessageDialog(null, "Configurações salvas.");
        dispose();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConfiguracoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClaro;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnEscuro;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JCheckBox cBoxLavaNao;
    private javax.swing.JCheckBox cBoxLavaSim;
    private javax.swing.JCheckBox cBoxTelNao;
    private javax.swing.JCheckBox cBoxTelSim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea labelComQuebra;
    private javax.swing.JTextArea labelComQuebra2;
    private javax.swing.JSpinner spinQntDias;
    private javax.swing.JSpinner spinQntLava;
    // End of variables declaration//GEN-END:variables
}
