/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.rm.lavarapidorm.gui;

import com.rm.lavarapidorm.persistencia.*;
import java.awt.*;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Renato
 */
public class TelaAtualizarUsuario extends javax.swing.JFrame {
    public Usuario usuarioAtual;
    private static boolean isOpen = false;
    private Dimension initialSize = this.getSize();
    /**
     * Creates new form TelaAtualizarUsuario
     */
    public TelaAtualizarUsuario() {
        initComponents();
        initialSize = this.getSize();
        ZoomUtils.resetStoredProperties();
        ZoomUtils.storeOriginalProperties(jPanel1);
        
        ImageIcon img = new ImageIcon(getClass().getResource("/icone.png"));        
        setIconImage(img.getImage());
       
        btnEditar.setName("ignorar");
        lblAzul.setName("ignorar");
        estrela1.setName("ignorar");
        estrela2.setName("ignorar");
        estrela3.setName("ignorar");
        estrela4.setName("ignorar");
        estrela5.setName("ignorar");
        estrela6.setName("ignorar");
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                isOpen = false;
            }

            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                isOpen = false;
            }
        });    
    }
    
    public TelaAtualizarUsuario(Usuario u) {
        initComponents();
        setLocationRelativeTo(null); 
        initialSize = this.getSize();
        ZoomUtils.resetStoredProperties();
        ZoomUtils.storeOriginalProperties(jPanel1);
        
        ImageIcon img = new ImageIcon(getClass().getResource("/icone.png"));        
        setIconImage(img.getImage());
        
        usuarioAtual = u;
        txtNome.setText(usuarioAtual.getNome());
        txtLogin.setText(usuarioAtual.getLogin());
        
        btnEditar.setName("ignorar");
        lblAzul.setName("ignorar");
        estrela1.setName("ignorar");
        estrela2.setName("ignorar");
        estrela3.setName("ignorar");
        estrela4.setName("ignorar");
        estrela5.setName("ignorar");
        estrela6.setName("ignorar");
        
        switch (usuarioAtual.getTipo()) {
        case "Usuário": radioUsuario.setSelected(true); break;
        case "Operador": radioOperador.setSelected(true); break;
        case "Administrador": radioAdm.setSelected(true); break;
     }
        
    this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                isOpen = false;
            }

            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                isOpen = false;
            }
        });
    }
     
    @Override
    public void setVisible(boolean b) {
        TelaLogin.temaEscuro(this, getContentPane());
        if (!isOpen) {
            isOpen = true;
            super.setVisible(b);
        } else {
            JOptionPane.showMessageDialog(this, "Esta janela já está aberta!");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAzul = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        estrela2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        estrela1 = new javax.swing.JLabel();
        estrela3 = new javax.swing.JLabel();
        estrela5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        estrela6 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        radioUsuario = new javax.swing.JRadioButton();
        radioOperador = new javax.swing.JRadioButton();
        radioAdm = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        estrela4 = new javax.swing.JLabel();
        txtSenhaSec = new javax.swing.JPasswordField();
        CBoxSenha = new javax.swing.JCheckBox();
        txtSenha = new javax.swing.JPasswordField();
        txtSenhaConf = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar usuário");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        lblAzul.setFont(new java.awt.Font("Segoe UI", 1, 33)); // NOI18N
        lblAzul.setForeground(new java.awt.Color(51, 102, 255));
        lblAzul.setText("Editar Usuário");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Login");
        jLabel3.setToolTipText("Obrigatório");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        txtLogin.setToolTipText("Login, campo que será usado para acessar a conta");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nome");
        jLabel4.setToolTipText("Obrigatório");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Nova Senha");
        jLabel7.setToolTipText("Obrigatório");

        btnEditar.setBackground(new java.awt.Color(255, 153, 51));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.setToolTipText("Confirmar edição");
        btnEditar.setMaximumSize(new java.awt.Dimension(152, 59));
        btnEditar.setPreferredSize(new java.awt.Dimension(152, 39));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVoltar.setText("< Voltar");
        btnVoltar.setToolTipText("Voltar à lista de Usuários");
        btnVoltar.setPreferredSize(new java.awt.Dimension(152, 39));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        estrela2.setForeground(new java.awt.Color(255, 0, 51));
        estrela2.setText("*");

        jLabel9.setText("Campo obrigatório");

        estrela1.setForeground(new java.awt.Color(255, 0, 51));
        estrela1.setText("*");

        estrela3.setForeground(new java.awt.Color(255, 0, 51));
        estrela3.setText("*");

        estrela5.setForeground(new java.awt.Color(255, 0, 51));
        estrela5.setText("*");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Confirmar senha");

        estrela6.setForeground(new java.awt.Color(255, 0, 51));
        estrela6.setText("*");

        radioUsuario.setText("Usuário");
        radioUsuario.setEnabled(false);
        radioUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        radioOperador.setText("Operador");
        radioOperador.setEnabled(false);
        radioOperador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        radioAdm.setText("Administrador");
        radioAdm.setEnabled(false);
        radioAdm.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(radioUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioOperador)
                .addGap(56, 56, 56)
                .addComponent(radioAdm))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAdm)
                    .addComponent(radioOperador)
                    .addComponent(radioUsuario)))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Senha atual");
        jLabel5.setToolTipText("Obrigatório");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        estrela4.setForeground(new java.awt.Color(255, 0, 51));
        estrela4.setText("*");

        txtSenhaSec.setMinimumSize(new java.awt.Dimension(64, 32));
        txtSenhaSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaSecActionPerformed(evt);
            }
        });
        txtSenhaSec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaSecKeyPressed(evt);
            }
        });

        CBoxSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CBoxSenha.setText("Exibir senhas");
        CBoxSenha.setToolTipText("Exibir/Ocultar senha");
        CBoxSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBoxSenhaActionPerformed(evt);
            }
        });

        txtSenha.setMaximumSize(new java.awt.Dimension(178, 22));
        txtSenha.setMinimumSize(new java.awt.Dimension(64, 32));
        txtSenha.setPreferredSize(new java.awt.Dimension(178, 22));
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaKeyPressed(evt);
            }
        });

        txtSenhaConf.setMaximumSize(new java.awt.Dimension(178, 22));
        txtSenhaConf.setMinimumSize(new java.awt.Dimension(64, 32));
        txtSenhaConf.setPreferredSize(new java.awt.Dimension(178, 22));
        txtSenhaConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaConfActionPerformed(evt);
            }
        });
        txtSenhaConf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaConfKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAzul)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estrela5))
                            .addComponent(txtSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estrela6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtSenhaConf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))
                    .addComponent(txtLogin, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNome)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSenhaSec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(estrela1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estrela2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estrela3)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(estrela4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CBoxSenha)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblAzul)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estrela1)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(estrela2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(estrela3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(estrela4)
                    .addComponent(CBoxSenha))
                .addGap(1, 1, 1)
                .addComponent(txtSenhaSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(estrela6))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(estrela5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSenhaConf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed

    }//GEN-LAST:event_jLabel3MousePressed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        UsuarioBD usuarioBD = new UsuarioBD();

        char[] senhaNovaChars = txtSenha.getPassword();
        char[] senhaConfirmaChars = txtSenhaConf.getPassword();
        char[] senhaAtualChars = txtSenhaSec.getPassword();

        String senhaNova = new String(senhaNovaChars);
        String senhaConfirmada = new String(senhaConfirmaChars);
        String senhaAtualDigitada = new String(senhaAtualChars);

        // Segurança: limpar arrays
        Arrays.fill(senhaNovaChars, '\0');
        Arrays.fill(senhaConfirmaChars, '\0');
        Arrays.fill(senhaAtualChars, '\0');
        
        
        if (txtLogin.getText().trim().isEmpty() || senhaNova.trim().isEmpty() ||
            txtNome.getText().trim().isEmpty() || senhaConfirmada.trim().isEmpty()) { 
            JOptionPane.showMessageDialog(this, "Os campos não podem estar em branco.", "Erro", JOptionPane.ERROR_MESSAGE); return;}  
        
        if (!usuarioBD.verificarSenha(senhaAtualDigitada, usuarioAtual.getSenha())) { 
            // Se o campo "Senha Atual" estiver incorreto, mostra um aviso
            JOptionPane.showMessageDialog(this, "Senha incorreta.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!senhaNova.trim().equals(senhaConfirmada.trim())) { JOptionPane.showMessageDialog(this, "As senhas não correspondem.", "Erro", JOptionPane.ERROR_MESSAGE); return; }
        
        if (usuarioBD.loginJaExiste(txtLogin.getText().trim(), usuarioAtual.getId())) {
            JOptionPane.showMessageDialog(this, "Esse login já está em uso por outro usuário.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }      
        
        // Fazendo a edição do usuário...
        usuarioAtual.setLogin(txtLogin.getText().trim());
        usuarioAtual.setNome(txtNome.getText().trim());
        usuarioAtual.setSenha(usuarioBD.gerarHash(senhaNova.trim())); 

        // Método para salvar as alterações no banco
        usuarioBD.atualizarUsuario(usuarioAtual);

        JOptionPane.showMessageDialog(this, "Usuario alterado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        dispose(); // Fecha a tela de edição
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        TelaLogin.temaEscuro(this, getContentPane());
    }//GEN-LAST:event_formWindowGainedFocus

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
/*  Dimension newSize = this.getSize();
    double scaleX = newSize.getWidth() / initialSize.getWidth();
    double scaleY = newSize.getHeight() / initialSize.getHeight();
    double scale = Math.min(scaleX, scaleY); // Escala proporcional
    
    ZoomUtils.updateComponentSize(jPanel1, scale); */
    }//GEN-LAST:event_formComponentResized

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MousePressed

    private void txtSenhaSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaSecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaSecActionPerformed

    private void txtSenhaSecKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaSecKeyPressed

    }//GEN-LAST:event_txtSenhaSecKeyPressed

    private void CBoxSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBoxSenhaActionPerformed
        if (CBoxSenha.isSelected()) {
            txtSenhaSec.setEchoChar((char) 0);
            txtSenha.setEchoChar((char) 0);
            txtSenhaConf.setEchoChar((char) 0);
        } else {
            txtSenhaSec.setEchoChar('*');
            txtSenha.setEchoChar('*');
            txtSenhaConf.setEchoChar('*');
        }
    }//GEN-LAST:event_CBoxSenhaActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaKeyPressed

    private void txtSenhaConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaConfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaConfActionPerformed

    private void txtSenhaConfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaConfKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaConfKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtualizarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CBoxSenha;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel estrela1;
    private javax.swing.JLabel estrela2;
    private javax.swing.JLabel estrela3;
    private javax.swing.JLabel estrela4;
    private javax.swing.JLabel estrela5;
    private javax.swing.JLabel estrela6;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAzul;
    private javax.swing.JRadioButton radioAdm;
    private javax.swing.JRadioButton radioOperador;
    private javax.swing.JRadioButton radioUsuario;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JPasswordField txtSenhaConf;
    private javax.swing.JPasswordField txtSenhaSec;
    // End of variables declaration//GEN-END:variables
}
