/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.lavafacil.gui;

import com.lavafacil.persistencia.Carros;
import com.lavafacil.persistencia.CarrosBD;
import java.awt.*;
import java.awt.event.*;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Renato
 */
public class TelaListagem extends javax.swing.JFrame {
       private static boolean isOpen = false;
       private Dimension initialSize = this.getSize();
    /**
     * Creates new form TelaListagem
     */
    public TelaListagem() {
        initComponents();
        setLocationRelativeTo(null); 
        initialSize = this.getSize();
        ZoomUtils.resetStoredProperties();
        ZoomUtils.storeOriginalProperties(jPanel1);
        
        ImageIcon img = new ImageIcon(getClass().getResource("/icone.png"));        
        setIconImage(img.getImage());
        
        CarrosBD CBD = new CarrosBD();
        
        btnAdicionarLavagem.setName("ignorar");
        btnExcluirCarro.setName("ignorar");
        btnEditar.setName("ignorar");
        btnListaLavagens.setName("ignorar");
    
    txtPesquisa.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER && e.getModifiers() == 0) {
                    btnPesquisar.doClick();
                }
            }
        });
        
    CBMetodo.addActionListener(e -> {
        String selected = (String) CBMetodo.getSelectedItem();
        switch (selected) {
            case "Todos":         
                lblPesquisar.setVisible(false);
                txtPesquisa.setVisible(false);
                btnPesquisar.setVisible(false);
                preencheTabela(CBD.listar());
                break;
            case "Carros que não retornaram":
                lblPesquisar.setVisible(false);
                txtPesquisa.setVisible(false);
                btnPesquisar.setVisible(false);
                preencheTabela(CBD.listar(txtPesquisa.getText(), 5));
                break;
            default:
                lblPesquisar.setVisible(true);
                txtPesquisa.setVisible(true);
                btnPesquisar.setVisible(true);
                break;
        }
    });
    
    this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                isOpen = false;
            }

            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                isOpen = false;
            }
        });
}
    @Override
    public void setVisible(boolean b) {
        TelaLogin.temaEscuro(this, getContentPane());
        if (!isOpen) {
            isOpen = true;
            super.setVisible(b);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCarro = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        CBMetodo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnAdicionarLavagem = new javax.swing.JButton();
        btnExcluirCarro = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnListaLavagens = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblPesquisar = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listagem de Carros");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tabelaCarro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaCarro);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Método de pesquisa:");

        CBMetodo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBMetodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Placa carro", "Nome cliente", "Telefone", "Marca do carro", "Carros que não retornaram", "Todos" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Pesquisar carros");

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVoltar.setText("< Voltar");
        btnVoltar.setToolTipText("Voltar à tela inicial");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnAdicionarLavagem.setBackground(new java.awt.Color(51, 255, 204));
        btnAdicionarLavagem.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnAdicionarLavagem.setText("Adicionar lavagem");
        btnAdicionarLavagem.setToolTipText("Incrementar em 1 às visitas do carro selecionado");
        btnAdicionarLavagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarLavagemActionPerformed(evt);
            }
        });

        btnExcluirCarro.setBackground(new java.awt.Color(255, 0, 0));
        btnExcluirCarro.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnExcluirCarro.setText("Excluir carro");
        btnExcluirCarro.setToolTipText("Deletar carro selecionado");
        btnExcluirCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCarroActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(255, 153, 51));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setToolTipText("Editar carro selecionado");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnListaLavagens.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnListaLavagens.setText("Lavagens");
        btnListaLavagens.setToolTipText("Ir a lista de lavagens registradas");
        btnListaLavagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaLavagensActionPerformed(evt);
            }
        });

        jPanel5.setPreferredSize(new java.awt.Dimension(900, 33));

        lblPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPesquisar.setText("Pesquisar:");

        txtPesquisa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setToolTipText("Pesquisa com base no texto e método inseridos");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(lblPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisar)
                .addGap(8, 8, 8))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesquisar)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CBMetodo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAdicionarLavagem, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirCarro, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListaLavagens, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CBMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarLavagem, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListaLavagens, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        TelaLogin.temaEscuro(this, getContentPane());
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        CarrosBD CBD = new CarrosBD();
        preencheTabela(CBD.listar());
    }//GEN-LAST:event_formWindowOpened

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnAdicionarLavagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarLavagemActionPerformed
        if (tabelaCarro.getSelectedRow() >= 0) {
           if (JOptionPane.showConfirmDialog(null, "Adicionar lavagem?") == 0) {
            int id = Integer.parseInt(tabelaCarro.getValueAt(tabelaCarro.getSelectedRow(), 0).toString());
            CarrosBD CBD = new CarrosBD();
            TelaCadastroLavagem TCL = new TelaCadastroLavagem(CBD.buscarCarroPorId(id));
            TCL.setVisible(true);
            dispose(); }
           }
        else{ JOptionPane.showMessageDialog(rootPane, "Selecione um carro!"); }
    }//GEN-LAST:event_btnAdicionarLavagemActionPerformed

    private void btnExcluirCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCarroActionPerformed
       if (tabelaCarro.getSelectedRow() >= 0) {
            CarrosBD CBD = new CarrosBD();
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir o carro de " + tabelaCarro.getValueAt(tabelaCarro.getSelectedRow(), 2) + "?") == 0) {
           CBD.excluirCarro(CBD.buscarCarroPorId(Integer.parseInt(tabelaCarro.getValueAt(tabelaCarro.getSelectedRow(), 0).toString()))); 
            preencheTabela(CBD.listar()); }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um carro!");
        }
    }//GEN-LAST:event_btnExcluirCarroActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       if (tabelaCarro.getSelectedRow() >= 0) {
            CarrosBD CBD = new CarrosBD();
            TelaEditar TE = new TelaEditar(CBD.buscarCarroPorId(Integer.parseInt(tabelaCarro.getValueAt(tabelaCarro.getSelectedRow(), 0).toString())));
            TE.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um carro!");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnListaLavagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaLavagensActionPerformed
        TelaConsultaLavagem TCL = new TelaConsultaLavagem();
        TCL.setVisible(true);        
    }//GEN-LAST:event_btnListaLavagensActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        CarrosBD CBD = new CarrosBD();

        switch ((String) CBMetodo.getSelectedItem()) {
            case "Placa carro": preencheTabela(CBD.listar(txtPesquisa.getText(), 1)); break;

            case "Nome cliente": preencheTabela(CBD.listar(txtPesquisa.getText(), 2)); break;

            case "Telefone": preencheTabela(CBD.listar(txtPesquisa.getText(), 3)); break;

            case "Marca do carro": preencheTabela(CBD.listar(txtPesquisa.getText(), 4)); break;}
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
/*  Dimension newSize = this.getSize();
    double scaleX = newSize.getWidth() / initialSize.getWidth();
    double scaleY = newSize.getHeight() / initialSize.getHeight();
    double scale = Math.min(scaleX, scaleY); // Escala proporcional
    
    ZoomUtils.updateComponentSize(jPanel1, scale); */
    }//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaListagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBMetodo;
    private javax.swing.JButton btnAdicionarLavagem;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluirCarro;
    private javax.swing.JButton btnListaLavagens;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JTable tabelaCarro;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
public void preencheTabela(List<Carros> carros){ 
    
    if (TelaLogin.conf == 2 ) {
    String columns[] = {"Id", "Placa", "Cliente", "Telefone", "Carro", "Lavagens (todas)", "Completas", "Grátis", "Tempo Limite", "Observações"};
    String dados[][] = new String[carros.size()][columns.length];
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");  

    int i = 0;
    for (Carros c : carros) {
        Timestamp dataRegistro = c.getTempoLimite();
        String dataFormatada = "";

        if (dataRegistro != null) {
            Timestamp t = Timestamp.valueOf("1970-01-01 00:00:00");
            if (!dataRegistro.equals(t)) {
            LocalDateTime localDateTime = dataRegistro.toLocalDateTime(); 
            dataFormatada = localDateTime.format(formatter); } 
            else { dataFormatada = "N/A"; }
        }

        dados[i] = new String[]{ 
            String.valueOf(c.getId()), 
            c.getPlaca(),
            c.getNomeCliente(),
            c.getTelefone(),
            c.getMarcaCarro(),
            String.valueOf(c.getLavagens()),
            String.valueOf(c.getVisitas()),
            String.valueOf(c.getGratis()),
            dataFormatada,
            c.getObservacoes()
        };              
        i++;
    }

    DefaultTableModel model = new DefaultTableModel(dados, columns) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;  // Não permite edição direta das outras células
        }
    };
    tabelaCarro.setModel(model);
 }    
    else {      
        String columns[] = {"Id", "Placa", "Cliente", "Telefone", "Carro", "Lavagens (todas)", "Completas", "Grátis", "Tempo Limite", "Observações"};
        String dados[][] = new String[carros.size()][columns.length];
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");  
    
      int i=0;
      for(Carros c: carros){
        Timestamp dataRegistro = c.getTempoLimite();
        String dataFormatada = "", telefone;
        
        if (TelaInicial.telefone) { telefone = c.getTelefone();} else { telefone = "xx xxxxx-xxxx";}
        
        if (dataRegistro != null) {
            Timestamp t = Timestamp.valueOf("1970-01-01 00:00:00");
            if (!dataRegistro.equals(t)) {
            LocalDateTime localDateTime = dataRegistro.toLocalDateTime(); 
            dataFormatada = localDateTime.format(formatter); } 
            else { dataFormatada = "N/A"; }
        }
          dados[i] = new String[]{ 
              String.valueOf(c.getId()), 
              c.getPlaca(),
              c.getNomeCliente(),
              telefone,
              c.getMarcaCarro(),
              String.valueOf(c.getLavagens()),
              String.valueOf(c.getVisitas()),
              String.valueOf(c.getGratis()),
              dataFormatada,
              c.getObservacoes()};              
          i++;
      }
      
      DefaultTableModel model = new DefaultTableModel(dados, columns){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
      tabelaCarro.setModel(model);  } 
 }
}