/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.lavafacil.gui;

import com.lavafacil.persistencia.UsuarioBD;
import com.lavafacil.persistencia.Usuario;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Renato
 */
public class TelaLogin extends javax.swing.JFrame {
      public static int conf = 0;
      public static String l = "", s = "";
      public static String tema = "false";
      private Dimension initialSize;
      ImageIcon iconClaro = new ImageIcon(getClass().getResource("/claro.png"));
      ImageIcon iconEscuro = new ImageIcon(getClass().getResource("/escuro.png"));
        
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        setLocationRelativeTo(null); 
        initialSize = this.getSize();
        ZoomUtils.resetStoredProperties();
        ZoomUtils.storeOriginalProperties(jPanel1);
        
        btnTema.setIcon(iconClaro);
        
        ImageIcon img = new ImageIcon(getClass().getResource("/icone.png"));        
        setIconImage(img.getImage());
        
        lblLava.setName("ignorar");
        
        txtSenhaSec.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER && e.getModifiers() == 0) {
                    btnLogin.doClick();
                }
            }
        });
        
        txtLogin.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER && e.getModifiers() == 0) {
                    btnLogin.doClick();
                }
            }
        });        
    }
    
    public TelaLogin(String tem) {
        initComponents();
        tema = tem;
        setLocationRelativeTo(null); 
        initialSize = this.getSize();
        
        btnTema.setIcon(iconClaro);
        
        ImageIcon img = new ImageIcon(getClass().getResource("/icone.png"));        
        setIconImage(img.getImage());
        
        lblLava.setName("ignorar");
        
        txtSenhaSec.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER && e.getModifiers() == 0) {
                    btnLogin.doClick();
                }
            }
        });
        
        txtLogin.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER && e.getModifiers() == 0) {
                    btnLogin.doClick();
                }
            }
        });   
    }
    
    
                 @Override
    public void setVisible(boolean b) {
        TelaLogin.temaEscuro(this, getContentPane());
        super.setVisible(b);
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblLava = new javax.swing.JLabel();
        txtSenhaSec = new javax.swing.JPasswordField();
        txtLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CBoxSenha = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        btnTema = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LavaFacil");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Login:");

        lblLava.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblLava.setForeground(new java.awt.Color(0, 153, 255));
        lblLava.setText("LavaFacil");
        lblLava.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblLavaMousePressed(evt);
            }
        });

        txtSenhaSec.setMinimumSize(new java.awt.Dimension(64, 32));
        txtSenhaSec.setPreferredSize(new java.awt.Dimension(64, 35));
        txtSenhaSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaSecActionPerformed(evt);
            }
        });
        txtSenhaSec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaSecKeyPressed(evt);
            }
        });

        txtLogin.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtLogin.setNextFocusableComponent(txtSenhaSec);
        txtLogin.setPreferredSize(new java.awt.Dimension(64, 35));
        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Senha:");

        CBoxSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CBoxSenha.setText("Exibir senha");
        CBoxSenha.setToolTipText("Exibir/Ocultar senha");
        CBoxSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBoxSenhaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Insira seu login e senha");

        btnTema.setToolTipText("Alterar para o tema escuro");
        btnTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemaActionPerformed(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogin.setText("Entrar");
        btnLogin.setToolTipText("Login");
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogin.setMaximumSize(new java.awt.Dimension(151, 33));
        btnLogin.setMinimumSize(new java.awt.Dimension(82, 31));
        btnLogin.setPreferredSize(new java.awt.Dimension(150, 32));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSenhaSec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(21, 21, 21)
                        .addComponent(CBoxSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTema, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLava, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLava)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addComponent(btnTema, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBoxSenha)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenhaSec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (tema.equals("true")) { btnTema.setIcon(iconClaro);  }
        else { btnTema.setIcon(iconEscuro); }        
    }//GEN-LAST:event_formWindowOpened

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
   /* Dimension newSize = this.getSize();
    double scaleX = newSize.getWidth() / initialSize.getWidth();
    double scaleY = newSize.getHeight() / initialSize.getHeight();
    double scale = Math.min(scaleX, scaleY); // Escala proporcional

    ZoomUtils.updateComponentSize(jPanel1, scale); */
    }//GEN-LAST:event_formComponentResized

    private void lblLavaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLavaMousePressed

    }//GEN-LAST:event_lblLavaMousePressed

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void CBoxSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBoxSenhaActionPerformed
        if (CBoxSenha.isSelected()) {
            txtSenhaSec.setEchoChar((char) 0);
        } else {
            txtSenhaSec.setEchoChar('*');
        }
    }//GEN-LAST:event_CBoxSenhaActionPerformed

    private void btnTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemaActionPerformed
        if (tema.equals("false")) { tema="true"; btnTema.setIcon(iconClaro); btnTema.setToolTipText("Alterar para o tema claro");}
        else { tema="false"; btnTema.setIcon(iconEscuro); btnTema.setToolTipText("Alterar para o tema escuro"); }
        temaEscuro(this, getContentPane());
    }//GEN-LAST:event_btnTemaActionPerformed

    private void txtSenhaSecKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaSecKeyPressed

    }//GEN-LAST:event_txtSenhaSecKeyPressed

    private void txtSenhaSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaSecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaSecActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        Usuario usuario = new Usuario();
        UsuarioBD u = new UsuarioBD();
        try{
            char[] passwordChars = txtSenhaSec.getPassword();
            String password = new String(passwordChars);
            usuario = u.validarUsuario(txtLogin.getText(), password);
            if (usuario != null) {

                JOptionPane.showMessageDialog(null, "Olá " + usuario.getNome() +
                    ", sua permissão é " + usuario.getTipo() + "(a). Seja bem-vindo!");

                TelaInicial TI = new TelaInicial(usuario);

                switch (usuario.getTipo()) {
                    case "Usuário": conf = 0; l = usuario.getLogin(); s = usuario.getSenha(); TI.setVisible(true);  dispose(); break;
                    case "Operador": conf = 1; l = usuario.getLogin(); s = usuario.getSenha(); TI.setVisible(true); dispose(); break;
                    case "Administrador": conf = 2; l = usuario.getLogin(); s = usuario.getSenha(); TI.setVisible(true);  dispose();  break;
                }   }
                else { JOptionPane.showMessageDialog(null, "Nenhum usuário encontrado! Verifique se os dados estão corretos."); }
            }catch(Exception e){JOptionPane.showMessageDialog(this, "Ocorreu uma falha:\n" + e.getMessage());}
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CBoxSenha;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnTema;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLava;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenhaSec;
    // End of variables declaration//GEN-END:variables
public static void temaEscuro(JFrame frame, Container container) {
    // Configura o fundo do JFrame e JPanel
    Color fundoEscuro = new Color(46, 46, 46);
    Color fundoClaro = new Color(200, 200, 200);  // Cinza claro para os outros componentes
    Color fonteEscura = Color.BLACK;
    Color fonteClara = Color.WHITE;
    boolean modoEscuro = Boolean.parseBoolean(tema);
    
    if (frame != null) { 
        frame.getContentPane().setBackground(modoEscuro ? fundoEscuro : Color.WHITE);
    }

    for (Component c : container.getComponents()) {
        if (c instanceof JPanel) {
            // Alterar o fundo dos JPanels
            JPanel panel = (JPanel) c;
            panel.setBackground(modoEscuro ? fundoEscuro : Color.WHITE);
        } else if (c instanceof JLabel) { 
            // Alterar a cor dos JLabels
            JLabel label = (JLabel) c;
            if (!"ignorar".equals(label.getName())) {
            label.setForeground(modoEscuro ? fonteClara : fonteEscura); }
        } else if (c instanceof JButton) {
            // Alterar a cor dos JButtons
            JButton button = (JButton) c;
            if (!"ignorar".equals(button.getName())) {
            button.setBackground(modoEscuro ? fundoClaro : null); // Define o fundo como cinza claro ou o padrão
            }
        } else if (c instanceof JTextField) {
            // Alterar a cor dos JTextFields
            JTextField textField = (JTextField) c;
            textField.setBackground(modoEscuro ? fundoClaro : Color.WHITE);
        } else if (c instanceof JTextArea) {
            // Alterar a cor dos JTextFields
            JTextArea textArea = (JTextArea) c;
            if (!"ignorar".equals(textArea.getName())) {
            textArea.setBackground(modoEscuro ? fundoClaro : Color.WHITE); }
        } else if (c instanceof JComboBox) {
            // Alterar a cor dos JComboBox
            JComboBox comboBox = (JComboBox) c;
            comboBox.setBackground(modoEscuro ? fundoClaro : Color.WHITE);
        } else if (c instanceof JCheckBox) {
            // Alterar a cor dos JComboBox
            JCheckBox checkBox = (JCheckBox) c;
            checkBox.setBackground(modoEscuro ? fundoEscuro : Color.WHITE);
            checkBox.setForeground(modoEscuro ? fonteClara : fonteEscura);
        } else if (c instanceof JTable) {
            JTable table = (JTable) c;
            
            // Alterar o fundo e o texto da tabela
            table.setBackground(modoEscuro ? fundoEscuro : Color.WHITE);
            table.setForeground(modoEscuro ? fonteClara : fonteEscura);

            // Alterar a cor de seleção da tabela
            table.setSelectionBackground(modoEscuro ? new Color(70, 70, 70) : new Color(184, 207, 229));
            table.setSelectionForeground(modoEscuro ? fonteClara : fonteEscura);

            // Alterar a cor do cabeçalho da tabela
            JTableHeader header = table.getTableHeader();
            header.setBackground(modoEscuro ? fundoClaro : Color.LIGHT_GRAY);
            header.setForeground(modoEscuro ? fonteClara : fonteEscura);
            
            // Alterar fundo da tabela
            if (table.getParent() instanceof JViewport) {
            table.getParent().setBackground(modoEscuro ? fundoEscuro : Color.WHITE); }
            
            // (Opcional) Redesenhar a tabela para garantir que as mudanças sejam aplicadas
            table.repaint();
        } else if (c instanceof JRadioButton) {
            // Alterar a cor das JTables
            JRadioButton button = (JRadioButton) c;
            button.setBackground(modoEscuro ? fundoEscuro : Color.WHITE);
            button.setForeground(modoEscuro ? fonteClara : fonteEscura);
        }

        // Se houver outros containers aninhados, iterar neles também
        if (c instanceof Container) {
            temaEscuro(null, (Container) c);
        }
    }
 }
}
