/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.lavafacil.gui;

import com.lavafacil.persistencia.LavagensBD;
import com.lavafacil.persistencia.Lavagens;
import java.awt.*;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.time.DateTimeException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Renato
 */
public class TelaConsultaLavagem extends javax.swing.JFrame {
    private static boolean isOpen = false;
    private Dimension initialSize = this.getSize();

    /**
     * Creates new form ConsultaLavagem
     */
    public TelaConsultaLavagem() {
        initComponents();
        setLocationRelativeTo(null);
        initialSize = this.getSize();
        ZoomUtils.resetStoredProperties();
        ZoomUtils.storeOriginalProperties(jPanel1);
        
        ImageIcon img = new ImageIcon(getClass().getResource("/icone.png"));        
        setIconImage(img.getImage());
        
        // Criando um modelo separado para cada spinner de dia (1 a 31)
        SpinnerModel diaModel1 = new SpinnerNumberModel(1, 1, 31, 1);
        spinnerDia.setModel(diaModel1);

        SpinnerModel diaModel2 = new SpinnerNumberModel(1, 1, 31, 1);
        spinnerDiaEntre1.setModel(diaModel2);

        SpinnerModel diaModel3 = new SpinnerNumberModel(1, 1, 31, 1);
        spinnerDiaEntre2.setModel(diaModel3);

        // Criando um modelo separado para cada spinner de mês (1 a 12)
        SpinnerModel mesModel1 = new SpinnerNumberModel(1, 1, 12, 1);
        spinnerMes.setModel(mesModel1);

        SpinnerModel mesModel2 = new SpinnerNumberModel(1, 1, 12, 1);
        spinnerMesEntre1.setModel(mesModel2);

        SpinnerModel mesModel3 = new SpinnerNumberModel(1, 1, 12, 1);
        spinnerMesEntre2.setModel(mesModel3);

        // Criando um modelo separado para cada spinner de ano (2024 a 2100)
        SpinnerModel anoModel1 = new SpinnerNumberModel(2024, 2024, 2100, 1);
        spinnerAno.setModel(anoModel1);

        SpinnerModel anoModel2 = new SpinnerNumberModel(2024, 2024, 2100, 1);
        spinnerAnoEntre1.setModel(anoModel2);

        SpinnerModel anoModel3 = new SpinnerNumberModel(2024, 2024, 2100, 1);
        spinnerAnoEntre2.setModel(anoModel3);
        
    
    this.getRootPane().setDefaultButton(btnPesquisar);
            
    LavagensBD LBD = new LavagensBD();
    CBMetodo.addActionListener(e -> {
        String selected = (String) CBMetodo.getSelectedItem();
        switch (selected) {
            case "Data":
                mostrarComponentesData();
                break;
            case "Intervalo entre datas":
                mostrarComponentesDataEntre();
                break;
            case "Nome cliente":
                mostrarCampoNomeCliente();
                break;
            case "Placa carro":
                mostrarCampoPlacaCarro();
                break;
            case "ID do carro":
                mostrarCampoIdCarro();
                break;
            case "Marca do carro":
                mostrarCampoMarcaCarro();
                break;
            default:
                esconderTodosComponentes();                
                preencheTabela(LBD.listar());
                break;
        }
    });
    
            this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                isOpen = false;
            }

            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                isOpen = false;
            }
        });
    }
    @Override
    public void setVisible(boolean b) {
        esconderTodosComponentes();
        mostrarComponentesData();
        TelaLogin.temaEscuro(this, getContentPane());
        if (!isOpen) {
            isOpen = true;
            super.setVisible(b);
        } else {
            JOptionPane.showMessageDialog(this, "Esta janela já está aberta!");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLavagens = new javax.swing.JTable();
        btnPesquisar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CBMetodo = new javax.swing.JComboBox<>();
        btnExpandir = new javax.swing.JButton();
        lblValorTotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblValorConsulta = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        txtIdCarro = new javax.swing.JTextField();
        lblIdCarro = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        spinnerMesEntre1 = new javax.swing.JSpinner();
        spinnerAnoEntre1 = new javax.swing.JSpinner();
        lblAnoEntre2 = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        lblEntre = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        spinnerMes = new javax.swing.JSpinner();
        spinnerDia = new javax.swing.JSpinner();
        lblMesEntre1 = new javax.swing.JLabel();
        spinnerDiaEntre1 = new javax.swing.JSpinner();
        lblMesEntre2 = new javax.swing.JLabel();
        lblFinal = new javax.swing.JLabel();
        lblAnoEntre1 = new javax.swing.JLabel();
        lblDiaEntre2 = new javax.swing.JLabel();
        lblInicial = new javax.swing.JLabel();
        spinnerAnoEntre2 = new javax.swing.JSpinner();
        spinnerDiaEntre2 = new javax.swing.JSpinner();
        lblDia = new javax.swing.JLabel();
        lblAno = new javax.swing.JLabel();
        spinnerAno = new javax.swing.JSpinner();
        spinnerMesEntre2 = new javax.swing.JSpinner();
        lblMes = new javax.swing.JLabel();
        lblDiaEntre1 = new javax.swing.JLabel();
        txtMarcaCarro = new javax.swing.JTextField();
        lblMarcaCarro = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de lavagens");
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tabelaLavagens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Cliente", "Placa carro", "Telefone", "Nome do carro", "Valor", "Lavagem", "Observações", "Data"
            }
        ));
        jScrollPane1.setViewportView(tabelaLavagens);

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setToolTipText("Pesquisa com base no texto e método inseridos");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Pesquisar lavagens");

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVoltar.setText("< Voltar");
        btnVoltar.setToolTipText("Voltar à tela inicial");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Método de pesquisa:");

        CBMetodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Data", "Intervalo entre datas", "ID do carro", "Placa carro", "Nome cliente", "Marca do carro", "Todos" }));

        btnExpandir.setText("Expandir");
        btnExpandir.setToolTipText("Exibir informações da lavagem");
        btnExpandir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpandirActionPerformed(evt);
            }
        });

        lblValorTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Valor total:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setText("Valor consulta:");

        lblValorConsulta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jLayeredPane1.add(txtIdCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 2, 320, -1));

        lblIdCarro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIdCarro.setText("Informe o ID do carro:");
        jLayeredPane1.add(lblIdCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        lblCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCliente.setText("Informe o nome do cliente:");
        jLayeredPane1.add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jLayeredPane1.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 2, 320, -1));
        jLayeredPane1.add(spinnerMesEntre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));
        jLayeredPane1.add(spinnerAnoEntre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        lblAnoEntre2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAnoEntre2.setText("Ano");
        jLayeredPane1.add(lblAnoEntre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        lblPlaca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPlaca.setText("Informe a placa do carro:");
        jLayeredPane1.add(lblPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblEntre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEntre.setText("~~");
        jLayeredPane1.add(lblEntre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));
        jLayeredPane1.add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 2, 320, -1));

        spinnerMes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLayeredPane1.add(spinnerMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 40, -1, -1));

        spinnerDia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLayeredPane1.add(spinnerDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        lblMesEntre1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMesEntre1.setText("Mês");
        jLayeredPane1.add(lblMesEntre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));
        jLayeredPane1.add(spinnerDiaEntre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        lblMesEntre2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMesEntre2.setText("Mês");
        jLayeredPane1.add(lblMesEntre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        lblFinal.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblFinal.setText("Data final");
        jLayeredPane1.add(lblFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 80, -1));

        lblAnoEntre1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAnoEntre1.setText("Ano");
        jLayeredPane1.add(lblAnoEntre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        lblDiaEntre2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDiaEntre2.setText("Dia");
        jLayeredPane1.add(lblDiaEntre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        lblInicial.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblInicial.setText("Data inicial");
        jLayeredPane1.add(lblInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));
        jLayeredPane1.add(spinnerAnoEntre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 52, -1, -1));
        jLayeredPane1.add(spinnerDiaEntre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        lblDia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDia.setText("Dia");
        jLayeredPane1.add(lblDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        lblAno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAno.setText("Ano");
        jLayeredPane1.add(lblAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, -1));

        spinnerAno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLayeredPane1.add(spinnerAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 32, -1, -1));
        jLayeredPane1.add(spinnerMesEntre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        lblMes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMes.setText("Mês");
        jLayeredPane1.add(lblMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        lblDiaEntre1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDiaEntre1.setText("Dia");
        jLayeredPane1.add(lblDiaEntre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jLayeredPane1.add(txtMarcaCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 2, 320, -1));

        lblMarcaCarro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMarcaCarro.setText("Informe a marca do carro:");
        jLayeredPane1.add(lblMarcaCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CBMetodo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnImprimir))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnExpandir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValorConsulta)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValorTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPesquisar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(jLabel2)
                    .addComponent(btnImprimir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CBMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisar)
                    .addComponent(btnExpandir)
                    .addComponent(lblValorTotal)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(lblValorConsulta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        LavagensBD LBD = new LavagensBD();
        try {
        switch ((String) CBMetodo.getSelectedItem()) {
            case "Placa carro": preencheTabela(LBD.listar(txtPlaca.getText(), 1)); break;

            case "Nome cliente": preencheTabela(LBD.listar(txtCliente.getText(), 2)); break;
            
            case "Marca do carro": preencheTabela(LBD.listar(txtMarcaCarro.getText(), 3)); break;
            
            case "ID do carro": preencheTabela(LBD.listar(txtIdCarro.getText(), 4)); break;
            
            case "Data": LocalDateTime data = LocalDateTime.of( (int) spinnerAno.getValue(), (int) spinnerMes.getValue(), (int) spinnerDia.getValue(),  0, 0 ); 
            preencheTabela(LBD.listarData(data)); break;

            case "Intervalo entre datas":            
            LocalDateTime dataInicial = LocalDateTime.of((int) spinnerAnoEntre1.getValue(), (int) spinnerMesEntre1.getValue(), (int) spinnerDiaEntre1.getValue(), 0, 0 );
            LocalDateTime dataFinal = LocalDateTime.of((int) spinnerAnoEntre2.getValue(), (int) spinnerMesEntre2.getValue(), (int) spinnerDiaEntre2.getValue(), 23, 59, 59 );
            preencheTabela(LBD.listarEntreDatas(dataInicial, dataFinal)); break;
            
            case "Todos": preencheTabela(LBD.listar());} }
        catch (DateTimeException e) { JOptionPane.showMessageDialog(this, "Data inválida! \n" + e.getMessage(), "Data Inválida", JOptionPane.ERROR_MESSAGE); }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        LavagensBD LBD = new LavagensBD();
        
        BigDecimal valorTotal = LBD.somarValores();
        String valorTot = String.format("%.2f", valorTotal);
        lblValorTotal.setText("R$ " + valorTot);  
        lblValorTotal.setToolTipText("R$ " + valorTot);
        
        preencheTabela(LBD.listar());
    }//GEN-LAST:event_formWindowOpened

    private void btnExpandirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpandirActionPerformed
        if (!(tabelaLavagens.getSelectedRow() >= 0)) { JOptionPane.showMessageDialog(this, "Selecione uma lavagem!", "Lavagem não selecionada", JOptionPane.ERROR_MESSAGE); return; }
        
        LavagensBD LBD = new LavagensBD();
        int id = Integer.parseInt(tabelaLavagens.getValueAt(tabelaLavagens.getSelectedRow(), 0).toString());
        TelaInformacoesLavagem TIL = new TelaInformacoesLavagem(LBD.buscarLavagemPorId(id));
        TIL.setVisible(true);
    }//GEN-LAST:event_btnExpandirActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        TelaLogin.temaEscuro(this, getContentPane());
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
       if (!(tabelaLavagens.getSelectedRow() >= 0)) { JOptionPane.showMessageDialog(this, "Selecione uma lavagem!", "Lavagem não selecionada", JOptionPane.ERROR_MESSAGE); return; }       
       LavagensBD LBD = new LavagensBD();
       Lavagens lavagem = LBD.buscarLavagemPorId(Integer.parseInt(tabelaLavagens.getValueAt(tabelaLavagens.getSelectedRow(), 0).toString()));
       LBD.gerarPDFRecibo(lavagem);
        System.out.println("Foi, slá");
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
/*  Dimension newSize = this.getSize();
    double scaleX = newSize.getWidth() / initialSize.getWidth();
    double scaleY = newSize.getHeight() / initialSize.getHeight();
    double scale = Math.min(scaleX, scaleY); // Escala proporcional
    
    ZoomUtils.updateComponentSize(jPanel1, scale); */
    }//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaLavagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaLavagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaLavagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaLavagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultaLavagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBMetodo;
    private javax.swing.JButton btnExpandir;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblAnoEntre1;
    private javax.swing.JLabel lblAnoEntre2;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblDiaEntre1;
    private javax.swing.JLabel lblDiaEntre2;
    private javax.swing.JLabel lblEntre;
    private javax.swing.JLabel lblFinal;
    private javax.swing.JLabel lblIdCarro;
    private javax.swing.JLabel lblInicial;
    private javax.swing.JLabel lblMarcaCarro;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblMesEntre1;
    private javax.swing.JLabel lblMesEntre2;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblValorConsulta;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JSpinner spinnerAno;
    private javax.swing.JSpinner spinnerAnoEntre1;
    private javax.swing.JSpinner spinnerAnoEntre2;
    private javax.swing.JSpinner spinnerDia;
    private javax.swing.JSpinner spinnerDiaEntre1;
    private javax.swing.JSpinner spinnerDiaEntre2;
    private javax.swing.JSpinner spinnerMes;
    private javax.swing.JSpinner spinnerMesEntre1;
    private javax.swing.JSpinner spinnerMesEntre2;
    private javax.swing.JTable tabelaLavagens;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtIdCarro;
    private javax.swing.JTextField txtMarcaCarro;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
public void preencheTabela(List<Lavagens> lavagens){     
    String columns[] = {"Id", "Carro ID", "Cliente", "Placa carro", "Telefone", "Nome do carro", "Valor", "Lavagem", "Observações", "Data"};
    String dados[][] = new String[lavagens.size()][columns.length];
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");  
    double valorConsulta = 0.00;
    int i = 0;
    for (Lavagens l : lavagens) {
        valorConsulta = (valorConsulta+l.getValor());
        Timestamp dataRegistro = l.getData();
        String dataFormatada = "", completo;
        if (l.isCompleto()) { completo = "Completa"; } else { completo = "Outra"; }

        if (dataRegistro != null) {
            LocalDateTime localDateTime = dataRegistro.toLocalDateTime(); 
            dataFormatada = localDateTime.format(formatter);
        }
        
        // Formatar valor com 2 casas decimais
        String valorFormatado = String.format("%.2f", l.getValor());
        
        // Verificar se telefone, observações e marca do carro não são nulos
        String telefone = l.getTelefone() != null ? l.getTelefone() : "N/A";
        String observacoes = l.getObservacoes() != null ? l.getObservacoes() : "";
        String marcaCarro = l.getMarcaCarro() != null ? l.getMarcaCarro() : "";

        dados[i] = new String[]{ 
            String.valueOf(l.getId()), 
            String.valueOf(l.getIdCarro()),
            l.getNomeCliente(),
            l.getPlaca(),            
            telefone,
            marcaCarro,
            "R$ " + valorFormatado, // Valor formatado
            completo,
            observacoes,
            dataFormatada
        };              
        i++;
    }
    
    String valorCons = String.format("%.2f", valorConsulta);
    lblValorConsulta.setText("R$ " + valorCons);
    lblValorConsulta.setToolTipText("R$ " + valorCons);
    
    DefaultTableModel model = new DefaultTableModel(dados, columns) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;  // Não permite edição direta das outras células
        }
    };
    tabelaLavagens.setModel(model);
}

private void mostrarComponentesData() {
    esconderTodosComponentes();
    lblDia.setVisible(true);
    lblMes.setVisible(true);
    lblAno.setVisible(true);
    spinnerDia.setVisible(true);
    spinnerMes.setVisible(true);
    spinnerAno.setVisible(true);
}

private void mostrarComponentesDataEntre() {
    esconderTodosComponentes();    
    lblDiaEntre1.setVisible(true);
    lblDiaEntre2.setVisible(true);
    lblMesEntre1.setVisible(true);
    lblMesEntre2.setVisible(true);
    lblAnoEntre1.setVisible(true);
    lblAnoEntre2.setVisible(true);   
    
    spinnerDiaEntre1.setVisible(true);
    spinnerDiaEntre2.setVisible(true);
    spinnerMesEntre1.setVisible(true);
    spinnerMesEntre2.setVisible(true);
    spinnerAnoEntre1.setVisible(true);
    spinnerAnoEntre2.setVisible(true);   
    
    lblEntre.setVisible(true);
    lblInicial.setVisible(true);
    lblFinal.setVisible(true);
}

private void mostrarCampoNomeCliente() {
    esconderTodosComponentes();
    lblCliente.setVisible(true);
    txtCliente.setVisible(true);
}

private void mostrarCampoPlacaCarro() {
    esconderTodosComponentes();
    lblPlaca.setVisible(true);
    txtPlaca.setVisible(true);
}

private void mostrarCampoMarcaCarro() {
    esconderTodosComponentes();
    lblMarcaCarro.setVisible(true);
    txtMarcaCarro.setVisible(true);
}

private void mostrarCampoIdCarro() {
    esconderTodosComponentes();
    lblIdCarro.setVisible(true);
    txtIdCarro.setVisible(true);
}

private void esconderTodosComponentes() {
    /* Método de pesquisa "Data" */
    lblDia.setVisible(false);
    lblMes.setVisible(false);
    lblAno.setVisible(false);
    spinnerDia.setVisible(false);
    spinnerMes.setVisible(false);
    spinnerAno.setVisible(false);
    
    /* Método de pesquisa "Intervalo entre datas" */
    lblDiaEntre1.setVisible(false);
    lblDiaEntre2.setVisible(false);
    lblMesEntre1.setVisible(false);
    lblMesEntre2.setVisible(false);
    lblAnoEntre1.setVisible(false);
    lblAnoEntre2.setVisible(false);    
    spinnerDiaEntre1.setVisible(false);
    spinnerDiaEntre2.setVisible(false);
    spinnerMesEntre1.setVisible(false);
    spinnerMesEntre2.setVisible(false);
    spinnerAnoEntre1.setVisible(false);
    spinnerAnoEntre2.setVisible(false);    
    lblEntre.setVisible(false);
    lblInicial.setVisible(false);
    lblFinal.setVisible(false);

    /* Método de pesquisa "Nome cliente" */
    lblCliente.setVisible(false);
    txtCliente.setVisible(false);
    
    /* Método de pesquisa "Placa carro" */
    lblPlaca.setVisible(false);
    txtPlaca.setVisible(false);
    
    /* Método de pesquisa "Marca do carro" */
    lblMarcaCarro.setVisible(false);
    txtMarcaCarro.setVisible(false);
    
    /* Método de pesquisa "ID do carro" */
    lblIdCarro.setVisible(false);
    txtIdCarro.setVisible(false);
    
    this.revalidate(); 
    this.repaint(); 
 }
}
