/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.lavafacil.gui;

import com.lavafacil.persistencia.UsuarioBD;
import com.lavafacil.persistencia.Usuario;
import java.awt.*;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Renato
 */
public class TelaUsuarios extends javax.swing.JFrame {
    private static boolean isOpen = false;
    private Dimension initialSize = this.getSize();

    /**
     * Creates new form TelaUsuarios
     */
    public TelaUsuarios() {
        initComponents();
        setLocationRelativeTo(null); 
        initialSize = this.getSize();
        ZoomUtils.resetStoredProperties();
        ZoomUtils.storeOriginalProperties(jPanel1);
        
        ImageIcon img = new ImageIcon(getClass().getResource("/usuario.png"));        
        setIconImage(img.getImage());
        
        btnNovoUsuario.setName("ignorar");
        btnAtualizarUsuario.setName("ignorar");
        btnExcluirUsuario.setName("ignorar");
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                isOpen = false;
            }

            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                isOpen = false;
            }
        });
    }
    
    @Override
    public void setVisible(boolean b) {
        TelaLogin.temaEscuro(this, getContentPane());
        if (!isOpen) {
            isOpen = true;
            super.setVisible(b);
        } else {
            JOptionPane.showMessageDialog(this, "Esta janela já está aberta!");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaUsuario = new javax.swing.JTable();
        btnNovoUsuario = new javax.swing.JButton();
        btnAtualizarUsuario = new javax.swing.JButton();
        btnExcluirUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Usuários");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVoltar.setText("< Voltar");
        btnVoltar.setToolTipText("Voltar à tela inicial");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel1.setText("Usuários cadastrados");

        tabelaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaUsuario);

        btnNovoUsuario.setBackground(new java.awt.Color(51, 255, 0));
        btnNovoUsuario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnNovoUsuario.setText("Novo Usuário");
        btnNovoUsuario.setToolTipText("Cadastrar novo Usuário");
        btnNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoUsuarioActionPerformed(evt);
            }
        });

        btnAtualizarUsuario.setBackground(new java.awt.Color(255, 255, 0));
        btnAtualizarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnAtualizarUsuario.setText("Editar Usuário");
        btnAtualizarUsuario.setToolTipText("Editar Usuário existente");
        btnAtualizarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarUsuarioActionPerformed(evt);
            }
        });

        btnExcluirUsuario.setBackground(new java.awt.Color(255, 0, 0));
        btnExcluirUsuario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnExcluirUsuario.setText("Excluir Usuário");
        btnExcluirUsuario.setToolTipText("Deletar Usuário");
        btnExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNovoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(38, 38, 38)
                        .addComponent(btnAtualizarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(38, 38, 38)
                        .addComponent(btnExcluirUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAtualizarUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExcluirUsuario)
                        .addComponent(btnNovoUsuario)))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        UsuarioBD UBD = new UsuarioBD();
        preencheTabela(UBD.listar());
        TelaLogin.temaEscuro(this, getContentPane());
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoUsuarioActionPerformed
        TelaCadastroUsuario TCU = new TelaCadastroUsuario();
        if (TCU.isVisible()) { JOptionPane.showMessageDialog(rootPane, "Esta janela já está aberta!"); return; }
        TCU.setVisible(true);
    }//GEN-LAST:event_btnNovoUsuarioActionPerformed

    private void btnAtualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarUsuarioActionPerformed
        if (tabelaUsuario.getSelectedRow() >= 0) {  
            UsuarioBD UBD = new UsuarioBD();
            TelaAtualizarUsuario TAU = new TelaAtualizarUsuario(UBD.buscarUsuarioPorId(Integer.parseInt(tabelaUsuario.getValueAt(tabelaUsuario.getSelectedRow(), 0).toString()))); TAU.setVisible(true); }
        else{ JOptionPane.showMessageDialog(rootPane, "Selecione o usuário que deseja editar!"); }
    }//GEN-LAST:event_btnAtualizarUsuarioActionPerformed

    private void btnExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirUsuarioActionPerformed
    UsuarioBD UBD = new UsuarioBD();
    int selectedRow = tabelaUsuario.getSelectedRow(); // Obter a linha selecionada

    if (selectedRow >= 0) {
       String userRole = (String) tabelaUsuario.getValueAt(selectedRow, 4);
        if (!userRole.equals("Administrador")) {
           int userId = Integer.parseInt(tabelaUsuario.getValueAt(selectedRow, 0).toString());
           Usuario usuario = UBD.buscarUsuarioPorId(userId); // Chamar apenas uma vez

            if (usuario.getLogin().equals(TelaLogin.l) && usuario.getSenha().equals(TelaLogin.s)) {
                JOptionPane.showMessageDialog(rootPane, "Não é possível excluir a conta que está sendo utilizada!");
            } else {
                int confirm = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir o usuário de " + tabelaUsuario.getValueAt(selectedRow, 1) + "?");
                if (confirm == JOptionPane.YES_OPTION) { // Verifica se o usuário clicou em "Sim"
                    UBD.excluirUsuario(usuario); // Chamar método para excluir
                    // Atualizar a tabela ou realizar outra ação após a exclusão
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Não é possível excluir um Administrador!");
        }
    } else {
        JOptionPane.showMessageDialog(rootPane, "Selecione o usuário que deseja excluir!");
    }
    }//GEN-LAST:event_btnExcluirUsuarioActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
/*  Dimension newSize = this.getSize();
    double scaleX = newSize.getWidth() / initialSize.getWidth();
    double scaleY = newSize.getHeight() / initialSize.getHeight();
    double scale = Math.min(scaleX, scaleY); // Escala proporcional 
    
    ZoomUtils.updateComponentSize(jPanel1, scale); */
    }//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarUsuario;
    private javax.swing.JButton btnExcluirUsuario;
    private javax.swing.JButton btnNovoUsuario;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaUsuario;
    // End of variables declaration//GEN-END:variables
public void preencheTabela(List<Usuario> usuario){     
    if (TelaLogin.conf == 2 ) {
    String columns[] = {"Id", "Nome", "Login", "Senha", "Tipo"};
    String dados[][] = new String[usuario.size()][columns.length];

    int i = 0;
    for (Usuario u : usuario) {
        dados[i] = new String[]{ 
            String.valueOf(u.getId()), 
            u.getNome(),
            "***",
            "***",
            u.getTipo(),
        };              
        i++;
    }

    DefaultTableModel model = new DefaultTableModel(dados, columns) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;  // Não permite edição direta das outras células
        }
    };
    tabelaUsuario.setModel(model); 
     }
   }
}
